### ISSUE TITLE
[generate:theme] Improve theme generation

### ISSUE THREAD

**Issue by omero** [hechoendrupal/drupal-console#1125]
## Problem/Motivation

This @jameswilson tweet: https://twitter.com/jwilson3/status/656927236151451649

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/drupalconsole">@drupalconsole</a> can a theme have a console plugin to download and configure various dependencies (e.g. bootstrap sass, grunt, npm, bundler)?</p>&mdash; James Wilson (@jwilson3) <a href="https://twitter.com/jwilson3/status/656927236151451649">October 21, 2015</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Bring back the idea to include boilerplate code to create at least the basic minimal files to use:
Front-end dependency managers (bower, npm, bundle, gem) 
Basic files for task runners (gulp, grunt)

Examples:
`$ drupal generate:theme --npm --bower --gulp | --grunt` 

```
THEME_NAME/
├── bower.json
├── gulpfile.js | gruntfile.js
├── package.json
├── demo.info.yml
└── demo.theme
```

In the case of gulp or grunt files we need to include scaffolding for:
sass and js files
task (watch).
plugins (sass, concat, uglify, etc).

At BADCamp @jmolivas talked to @mortendk and he proposed the idea to use Drupal 8 theme vanilla http://mortendk.github.io/vanilla/ as starting point for theme generation.

The first phase of this command improvement is to cover the minimal setup, I would love to see opinion from front-end specialist about including other tools you use.

I ping @jameswilson, @jackbravo because you shown interest via twitter on this topic.

**Comment by jameswilson** [comment]
I think you mis interpreted what I was actually asking for.

What I want is the way to package a script wiht my theme that is Drupal console-aware php or yaml file that can provide custom instructions or commands to console that could be useful to do various tasks such as installing theme dependencies.

The workflow would be:

1) download the module (via drush or maybe Drupal console can do this?)
2) (optionally) be notified of newly found console commands.
3) execute those commands to finish the installation and configuration of the theme folder, such as installing npm, ruby, bundler, grunt/gulp etc, and downloading specific node/bundler modules  and ruby gems, etc.

**Comment by swim** [comment]
Really like the idea of providing a package detection mechanism.

Instead of providing a predefined theme skeleton such as vanilla; it would be nice if theme's could define their own packages. Drupal console could then define the standard in which to enable/ install them.

**Comment by mdrummond** [comment]
What would be particularly useful is if a theme could register whatever would be necessary to scaffold one or more subthemes. A theme might want to provide the option to generate a subtheme that uses Grunt OR Gulp (but probably not both in the same subtheme). This would be a considerable time saver, because while a theme can include a STARTERKIT folder that can be copied to create a subtheme, the process of renaming all the files and function names from STARTERKIT to whatever you want to name the subtheme is both time consuming and prone to error. My memory is that in D7, some popular base themes take care of this by having an associated module that can then extend drush to add commands to generate a subtheme, but that involves installing a module in addition to a theme. Not ideal. Some themes like Aurora use Yeoman to take care of the scaffolding, but that's yet another tool that needs to be installed. If a theme developer could simply ship their theme, and it could include whatever is needed for Drupal Console to generate the scaffolding for various subthemes, that would be hugely helpful. Particularly if the theme developer could configure the contents of a package.json or bower or Gulpfile that would be scaffolded.

**Comment by dustinleblanc** [comment]
I was just looking through the docs for something like this. Any idea of what is needed?

**Comment by mdrummond** [comment]
@dustinleblanc: I started working on allowing themes to add commands. A theme could then add its own generate command to build out a sub-theme. PR Need reviews: https://github.com/hechoendrupal/DrupalConsole/pull/1353

**Comment by mdrummond** [comment]
Just a note that #1353 has been merged, so I am going to try this out.

**Comment by enzolutions** [comment]
@mdrummond @omero we can close this issue?

**Comment by enzolutions** [comment]
second call @mdrummond @omero we can close this issue?
