### ISSUE TITLE
How to reinstall module?

### ISSUE THREAD

**Issue by UnbekanntesPferd** [hechoendrupal/drupal-console#1848]
Hi!
I generated a module via console, installed the module and then generated an entity for that module (generate:entity:content). After that I couldn't uninstall the module because I'm getting SQL errors like

```
[ERROR] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal8.team_entity' doesn't exist: SELECT
base_table.id AS id, base_table.id AS base_table_id
FROM
{team_entity} base_table
LIMIT 1 OFFSET 0; Array
(
)
```

Is there any way to update/reinstall the module? Or what would be the correct way of subsequently adding entities to a module

**Comment by mnico** [comment]
The correct way is adding entities to a module that is not installed yet. 
In this case try creating the table with a single column directly in the database and then uninstall the module.

**Comment by jmolivas** [comment]
@UnbekanntesPferd  @mnico we may need to review this old issue https://www.drupal.org/node/2629516

**Comment by UnbekanntesPferd** [comment]
Thank you :+1:

**Comment by mnico** [comment]
@jmolivas I don't know if that issue has to do with the same thing to this issue. In that issue talks about content types or bundles for nodes. In this case it's about entities content created in a module already installed, when this happens Drupal does not create the table and when you try uninstall the module fails because it tries to drop the table that not exists. 

I think this is not an issue of DC. But maybe exists a way to prevent or fix this with DC, for example a command that detect if an entity content exists but not its table and it tries to fix that.

**Comment by LOBsTerr** [comment]
I agree with mnico, It should be handled on the Drupal side https://www.drupal.org/project/drupal/issues/2563515

I am closing the issue. Feel free to reopen it.

**Comment by zhilevan** [comment]
I suggest check the module which you're tried to add entity , if it's enable don't add entity to it or ask user to disable the module then add Entity, I have the same problem in drupal console 1.8
