### ISSUE TITLE
Define Commands as Services

### ISSUE THREAD

**Issue by davidbarratt** [hechoendrupal/drupal-console#1947]
It would be really awesome if you could define a console command as a service:
http://symfony.com/doc/current/cookbook/console/commands_as_services.html

That way the command does _not_ have to be aware of the container, but can still receive dependencies. :)

**Comment by jmolivas** [comment]
@davidbarratt: Totally agree on this. 

We introduced a service container no long ago
https://github.com/hechoendrupal/DrupalConsole/blob/master/bin/drupal.php#L47

We started registering a few classes as services.
https://github.com/hechoendrupal/DrupalConsole/blob/master/services.yml 

We must test how this may impact the command discovery of customs commands since modules can add commands as webprofiler, commerce and metatag between others are doing it.

**Comment by jmolivas** [comment]
@davidbarratt Commands were registered as services in the DrupalConsole container  https://github.com/hechoendrupal/DrupalConsole/issues/2225

We are now registering command on the Drupal container, we started with this PR
https://github.com/hechoendrupal/DrupalConsole/pull/2583

**Comment by LOBsTerr** [comment]
@jmolivas it can be closed

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
