### ISSUE TITLE
Fish: init override create symbolic link message misleading, missing directory tree

### ISSUE THREAD

**Issue by diqidoq** [hechoendrupal/drupal-console#2087]
#### The Issue

It's just a small nit pick issue: The final drupal init--override message (tested under Debian 9 _sid_ and xterm) suggests for Fish to create a symbolic link, which is slidely misleading or has missing documentation for unexperienced users, since there is the directory tree missing, which the link wants to point to in that moment:

```
Fish: Create a symbolic link
ln -s ~/.console/drupal.fish ~/.config/fish/completions/drupal.fish

 $ ln -s ~/.console/drupal.fish ~/.config/fish/completions/drupal.fish
 ln: failed to create symbolic link '/home/username/.config/fish/completions/drupal.fish': No such file or directory
```
#### Further investigation shows:

```
$ ls ~/.config/fish/
ls: cannot access '/home/username/.config/fish/': No such file or directory
```

Here is the full installation terminal output: [as a new secret gist](https://gist.github.com/diqidoq/86291c1414c3ed1eefae873274419a47)
#### Questions to clear:
- Is this directory missing but was expected to be there ?
- Is this directory missing because the user has to create it and the info is just missing ?
- Is this behaviour Debian/xterm specific or can it be reproduced under different enviroments ?

**Comment by diqidoq** [comment]
If the second questions answer yes I would like to suggest to change the last message this way:

    Fish: Create a symbolic link (including the .config/fish directory)
    mkdir -p ~/.config/fish/completions/ && ln -s ~/.console/drupal.fish ~/.config/fish/completions/drupal.fish

**Comment by drugan** [comment]
I think you do not need to bother about `fish` or any other shell's autocompletion when you run `drupal init` command. The hint for creation symbolic link to `fish` actually is misleading on this stage because you don't have drupal 8 files downloaded and consequently don't have symfony's **ProcessBuilder** class available  yet. Moreover, the `drupal init` command is targeting `bash` shell not `fish`. It is hardcoded in the **../src/Command/InitCommand.php ->createAutocomplete()** method.

As far as I know bash has autocompletion by default and for me it works as a charm. All `drupal` commands are autocompleted by pressing **TAB** key twice even without drupal 8 files downloaded and symbolic link to fish created.
