### ISSUE TITLE
If module provided doesn't exist a PHP error in trigger on Drupal 8.1

### ISSUE THREAD

**Issue by RobWJacob** [hechoendrupal/drupal-console#2178]
i try to generate a form alter 

`drupal generate:form:alter --module="MyForm" --form-id="contact_message_contact"`

but i get an error

`PHP Fatal error:  Call to a member function getPath() on null in phar:///usr/local/bin/drupal/src/Helper/SiteHelper.php on line 260`

Drupal 8.1 stable, Debian 8, PHP 5.6.19-0+deb8u1

same error when i try generate:form

**Comment by jmolivas** [comment]
@RobWJacob does the module `MyForm` exists?

**Comment by RobWJacob** [comment]
yes, i generated it with
`drupal generate:module`

ah, the name of the module is 'myform' and not 'MyForm'
case closed :)

**Comment by jmolivas** [comment]
We must update this issue and use to report invalid module name when this happens?

**Comment by kylethebaker** [comment]
This also happens in `generate:entity:content` and is the same issue: if the module doesn't exist then `getModule(null)->getPath()` is called and the uncaught PHP exception is thrown.

My assumption is that this is happening in multiple commands that require the Module parameter unless they are doing their own error handling. I'm wondering, since `--module` seems like a common command argument, is there a way to handle the validation in one place rather than depending on each command to handle the checks?

It's too bad that symfony console doesn't let you specify a validation callback when creating the option, then:

    $this->addOption('module', ...)

could be replaced with something like:

    use Drupal\Console\Core\Helper\CommonOptions;
    CommonOptions::addOption("module", $this);

Where `::addOption` could handle adding both the option and the validation all one place. Unfortunately we can't do this, which means that each command would have to specify the options itself and then also deal with validation.

Does it make sense to add a `moduleExists($module)` to `Drupal\Console\Utils\Validator`? That way commands could at least have a single recommended way to do the validation rather than having to inject the `module_handler` service and check themselves. I see `getMissingModules` in the Validator, is that something that can be used to do this also?

**Comment by LOBsTerr** [comment]
I have started to work on it in this PR: https://github.com/hechoendrupal/drupal-console/pull/3642
Let's use this as a starting point. I'm not sure that it is a correct way to handle this problem, but I noticed that there are too many duplications of the same peace of code:
```
        $module = $input->getOption('module');  
        if (!$module) {  
            // @see Drupal\Console\Command\Shared\ModuleTrait::moduleQuestion  
            $module = $this->moduleQuestion($io);  
            $input->setOption('module', $module);  
        }  
```

Adding here a check for existence of the module is not the best place. So, I moved the code to the ModuleTrait and we will handle it in the single point. If it is ok, I will update other commands also.

**Comment by jmolivas** [comment]
@LOBsTerr like the idea, will check code and ping you back.

**Comment by jmolivas** [comment]
@LOBsTerr PR #3642 merged, we can go ahead and replicate/implement in the rest fo the commands.

**Comment by LOBsTerr** [comment]
@jmolivas I have finished the replacement in this PR https://github.com/hechoendrupal/drupal-console/pull/3653

**Comment by jmolivas** [comment]
PR #3653 merged
