### ISSUE TITLE
Missing Configuration File

### ISSUE THREAD

**Issue by nbunney** [hechoendrupal/drupal-console#2824]
I just did a completely fresh install of the Drupal Console using the instructions here: https://drupalconsole.com/ 
When I reach the step "drupal check" I get the following:

>  Checking requirements using file at:
>  /Users/nathan/.console/phpcheck.yml
>  [OK] Checks passed.  
>  [WARNING] Missing configuration file, possible paths:                                                                  
> - /Users/nathan/.console/config.yml
>   Execute "drupal init" command to generate one

there is a console/config.yml but nothing at .console

Moving this file from console to .console seems to fix the issue.

**Comment by jmolivas** [comment]
Did you answered yes to the first question? 

That is why was copied to `console` instead of `.console` that question must be answered yes when executing the init within a Drupal Site.

**Comment by nbunney** [comment]
Maybe I misunderstand the tool.  I thought this was a tool for creating Drupal installs.  Do I need to download Drupal first?  I used an early version of this tool (or one nearly identical) several months ago and it would ask me what version I wanted to use and then download that and create the directory and blam! there it was.  I guess what is confusing is that with no background your install instructions seem to be missing steps.  IMHO someone with no experience in Drupal should be able to come in and follow your steps and use your tool.  I did not find that to be true.

I really appreciate your efforts and am excited about this tool, just need to get over this noob usability hump.

**Comment by thijsvdanker** [comment]
@nbunney Just getting up and running but ran into the same issue.
There are basically two ways to set Drupal console up:

1. globally on your system
2. per project

The default settings when running `drupal init` place the config.yml file in the /console/ folder. This is useful when running drupal init from a project.

When setting up Drupal console globally to create Drupal installs, you have to respond *no* to the first question and use `.console`.

@jmolivas I agree with @nbunney that this is not really clear. One of the reasons is that (the documentation)[https://hechoendrupal.gitbooks.io/drupal-console/content/en/using/how-to-copy-configuration-files.html] reads that all files (including) config.yml will be in the `.console` directory when running `drupal init` but choosing all defaults in the dialog results in something different.

My suggestions:

1. make both scenarios clearer in the documentation.
2. change the wording of the question: `Copy at current directory console/config.yml?` to `Do you want to create a project specific configuration?`.. or something else that describes the reason why you would create the config.yml file in the current directory instead of globally.
