### ISSUE TITLE
[console] default options in config.yml seem to be ignored

### ISSUE THREAD

**Issue by marcvangend** [hechoendrupal/drupal-console#3162]
### Problem

The default value for the --uri option, as set in `myproject/console/config.yml`, seems to be ignored. This  may have to do with the fact that I used to have a global `/home/marc/.console/config.yml`.

### Situation

I'm running a Drupal 8.2.6 site with Drupal Console 1.0.0-rc15 (both local and launcher) on my development machine. The codebase is set up using a fork of https://github.com/drupal-composer/drupal-project; it is pretty similar but the drupal root dir is called "docroot" instead of "web" (probably irrelevant to this issue). The entire project is installed in `/srv/http/myproject`. Instead of using `/srv/http/myproject/docroot/sites/default`, I prefer to use the more explicit `/srv/http/myproject/docroot/sites/myproject` for my settings.php, but it is in fact a single-site install. There is a config file in `myproject/console/config.yml` where I uncommented the application.options.uri key and set it to `myproject.localhost`.

In the project root dir, when I run `drupal list` or `vendor/bin/drupal list`, it tells me "[ERROR] The specified database connection is not defined: default" and "[WARNING] In order to list all of the available commands you should install drupal first." Running `drupal list --uri=myproject.localhost` does result in the expected complete list of available commands. I noticed that `drupal settings:debug` starts with the line "Config file : /home/marc/.console/config.yml", even though that config file no longer exists. However the list of config keys does contain "options.uri    myproject.localhost", so I'm 100% sure that the correct config.yml is being read.

It seems to me that my Drupal Console is seriously confused about its configuration, and I have no idea how to fix it. Re-initializing console with `vendor/bin/drupal init --override` and `vendor/bin/drupal init --root=/srv/http/myproject/docroot/ --uri=myproject.localhost --override` didn't help. Your guidance is really appreciated.

**Comment by justinphilpott** [comment]
I second this, and wonder if there is any clarity on "[WARNING] In order to list all of the available commands you should install drupal first." ... I get this on fresh installs of latest versions as of writing:

"require": {
...
"drupal/console": "1.0.2",
...

Can anyone offer clarity on why this is happening? I will debug this and post conclusions.

**Comment by enzolutions** [comment]
@marcvangend how do you force Drupal to load that single site? did you use something like sites.php https://api.drupal.org/api/drupal/sites%21example.sites.php/8.2.x ?

The problem is because the settings.php is not found it by Drupal Console, and as you can expect the connection to the DB is not possible
