### ISSUE TITLE
Please reconsider regression of globally available drupal console.

### ISSUE THREAD

**Issue by chriscalip** [hechoendrupal/drupal-console#3237]
Latest updates on drupal console; made the globally available drupal console just a launcher tool to find and execute DrupalConsole. This change, effectively means it is now requirement for Drupal Console to be installed on a per-site basis.

This requirement puts in difficulties for devs doing local,dev,prod workflow. As it effectively requires us to diverge codebases (composer json, vendor/libraries, etc..) Also https://github.com/hechoendrupal/drupal-console/issues/3238 vendor drupalconsole might be vulnerable.

So please reconsider regression of globally available drupal console.

As a side effect vagrant/ansible/docker setups installing drupal console are broken/breaking because user base expectation is that effective globally available drupal console are still in play. 

**a.)** Will the drupal console team reconsider the regression of globally available drupal console?
**b.)** What was the latest version of drupal console that still had an effective globally available drupal console?

**Comment by CRYX2** [comment]
when installing Drupal Console as a dependency of the project is really a pain.

 It makes no sense to my mind, first install a global executable and then EVEN a local executable. 

Drush has been operating globally for years without problems.

**Comment by jmolivas** [comment]
#### Why we did this?
Managing dependencies per project make it easy to avoid conflict between them. Since DrupalConsole share same dependencies that Drupal and it also bootstraps to interact with the container and registered services.

#### Answering some of your questions and replying the comments:

> Will the drupal console team reconsider the regression of globally available drupal console?

This could be a huge task because in order to provide a global executable DrupalConsole must change dependencies to avoid conflict with Drupal dependencies.

> What was the latest version of drupal console that still had an effective globally available drupal console?

This change started on RC releases.

> It makes no sense to my mind, first install a global executable and then EVEN a local executable.

Install the Launcher aka global installer is not required you can omit this step and only do the per-site installation.

> As a side effect vagrant/ansible/docker setups installing drupal console are broken/breaking because user base expectation is that effective globally available drupal console are still in play.

Is a good practice to start your project using a project template like [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project)

#### Turn to questions

> This requirement puts in difficulties for devs doing local,dev,prod workflow. As it effectively requires us to diverge codebases (composer json, vendor/libraries, etc..) 

Could you elaborate more on this about the challenges ?

> At this moment, installing Drupal Console as a dependency for a project is really a pain.

Why is this a pain and what i make it difficult?

Finally I will address `vendor drupalconsole might be vulnerable` on it own issue #3238.

**Comment by Chi-teck** [comment]
> Drush has been operating globally for years without problems.
So now Drush recommends local installation as well. The main reason is upcoming Symfony update.
https://www.drupal.org/node/2712647

**Comment by cburschka-pwc** [comment]
> difficulties for devs doing local,dev,prod workflow. As it effectively requires us to diverge codebases

I don't know your workflow of course, but I don't see the need for that divergence. Even if you don't want DC on the production site (and it doesn't really do harm if left in), you can add it as a dev dependency and thus limit its installation to dev environments.

**Comment by chriscalip** [comment]
Thank you all for the response. I am closing this issue because from what I can tell drupalconsole now is effectively a per-drupal installation setup and will remain so. 
My hesitation on the new requirement was because I was not aware that composer.json can accept "dev dependency".
Thank you for the information, this option on composer.json lets me move forward with my projects using drupal console for local purposes only. My only recommendation is that the error message provides the information about dev dependency.
