### ISSUE TITLE
The service "console.migrate_rollback" has a dependency on a non-existent service "plugin.manager.migration".

### ISSUE THREAD

**Issue by albertski** [hechoendrupal/drupal-console#3410]
### Problem/Motivation
After uninstalling the migrate module when I run `drupal init` I get the following error:

```
[ERROR] The service "console.migrate_rollback" has a dependency on a non-existent service "plugin.manager.migration".
```

### How to reproduce
Migrate site
Uninstall migrate
Try to use drupal console

**Details to include:**
- Drupal version: `8.3.5`
- Console version:
```
drupal/console                        1.0.0-rc23   The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                   1.0.0-rc23   Drupal Console Core
drupal/console-dotenv                 0.3.0        Drupal Console Dotenv
drupal/console-en                     1.0.0-rc23   Drupal Console English Language
drupal/console-extend-plugin          0.9.0        Drupal Console Extend Plugin
```
- Console Launcher version: `Drupal Console version 1.0.0-rc23`
- Steps to reproduce
- Include screen-shot or video whenever necessary.

**Comment by cburschka-pwc** [comment]
I coincidentally ran into the same issue just this week. It seemed to be a
container-caching problem: The migrate commands are initially skipped if
the migrate module isn't installed, but if you install and remove it it
breaks the service container.

You could try the steps from #3354 to clear the cache...


On Jul 7, 2017 00:27, "Albert Jankowski" <notifications@github.com> wrote:

The service "console.migrate_rollback" has a dependency on a non-existent
service "plugin.manager.migration".

The issue title should comply with the following structure:
Problem/Motivation

After uninstalling the migrate module when I run drupal init I get the
following error:

[ERROR] The service "console.migrate_rollback" has a dependency on a
non-existent service "plugin.manager.migration".

How to reproduce

Migrate site
Uninstall migrate
Try to use drupal console

*Details to include:*

   - Drupal version: 8.3.5
   - Console version:

drupal/console                        1.0.0-rc23   The Drupal CLI. A
tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                   1.0.0-rc23   Drupal Console Core
drupal/console-dotenv                 0.3.0        Drupal Console Dotenv
drupal/console-en                     1.0.0-rc23   Drupal Console
English Language
drupal/console-extend-plugin          0.9.0        Drupal Console Extend Plugin


   - Console Launcher version: Drupal Console version 1.0.0-rc23
   - Steps to reproduce
   - Include screen-shot or video whenever necessary.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hechoendrupal/drupal-console/issues/3410>, or mute the
thread

**Comment by jmolivas** [comment]
@albertski try `drupal cr all`to rebuild dupal console caches, next DrupalConsole release will clear the caches once composer updates the project commands.

**Comment by albertski** [comment]
Thanks @cburschka-pwc ! Thanks @jmolivas `drupal cr all` fixed the issue.
