### ISSUE TITLE
[generate:theme] copy block layout from base_theme

### ISSUE THREAD

**Issue by kgaut** [hechoendrupal/drupal-console#3471]
When working on a new website, one of the first thing I do is to create an administration theme, usually based on seven (didn't gave a chance to **adminimal_theme** on d8 yet).

I use the command `drupal generate:theme` and give "**seven**" as base theme parameter. Once manually activated and set as administrative theme, it inherits of all the front theme's blocs. I have to manually remove them and set the administrative block layout from seven one block at the time.

Wouldn't it be nice if the command `drupal generate:theme`, copy the regions from the base theme and then copy the block layout ?

I don't know yet how to achieve this, I don't know ether if console is the right tool for that. This issue is for get ideas and feedbacks from other users.

**Comment by DuaelFr** [comment]
It could be a great option :)

**Comment by LOBsTerr** [comment]
The problem here, that a theme is missing the regions. I have checked other admin themes. They define the regions, even if the theme is based on seven.
Probably, it is a bug in Drupal core.
So, my proposal is add another option --base-regions. This option will be proposed, when the base theme is defined and it will copy regions from the base theme.
