### ISSUE TITLE
[site:install] site.status depends on non-existent system.manager

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3577]
This is a regression in 1.1.0; it doesn't happen in 1.0.2:

On a clean checkout of 8.4.2, install drupal/console and run `drupal site:install`.

DC will generate the following error: `[ERROR] The service "console.site_status" has a dependency on a non-existent service "system.manager".`

(The installation itself works.)

**Comment by Graloth** [comment]
I am getting the same error when running any drupal command. Would love to know if there is a solution to this.

**Comment by cburschka-pwc** [comment]
It seems to be happening on bootstrap whenever the site isn't installed. After it is installed, I see no error.

**Comment by Graloth** [comment]
How would I then go about getting it solved when adding drupal console to an existing site? I'd rather not run the install in case it overrides anything.

**Comment by danielrose28** [comment]
I see this error as well. I'm running D8 version 8.3.7 at the moment. I added DrupalConsole to my existing site via composer. When I run `drupal`, I see ```[ERROR] The service "console.site_status" has a
         dependency on a non-existent service
         "system.manager".```.

**Comment by jmolivas** [comment]
@cburschka-pwc @Graloth @danielrose28  Is showing exception when drupal is not yet installed

Fixed at this PR https://github.com/hechoendrupal/drupal-console/pull/3578 

This PR takes care of:
* Validating service `system.manager` exists when injecting into command.
* Remove error message if drupal not installed yet.

No need to display the message since DrupalConsole defaults to Launcher commands when site not yet installed.

**Comment by jmolivas** [comment]
New release v1.1.1 tagged including this fix.
Closing this one. Feel free to re-open if still happening after updating to the latest version.
