### ISSUE TITLE
[cron:execute] Cron execution does not run simplenews cron-queue

### ISSUE THREAD

**Issue by crifi** [hechoendrupal/drupal-console#3951]
### Problem/Motivation
I have a Drupal 8 an installed simplenews module. Simplenews sends nodes as newsletters to subscribers. The sending process works via drupal cron. If I queue a newsletter for sending, the newsletter won't be send if I use the cron command globally:

$ drupal cron:execute

If I call the specific cron module the newsletters are send:

$ drupal cron:execute simplenews

### How to reproduce

1. Install Drupal 8.6.1, drupal console 1.8.0 and simplenews  8.x-1.0-alpha3.
2. Create a simplenews newsletter.
3. Add a few newsletter subscribers.
4. Create a simplenews node for the created newsletter of step 2.
5. Send the node-newsletter after saving it.
6a. Call $ drupal cron:execute => The newsletter won't be send.
6b. Call $ drupal cron:execute simplenews => The newsletter will be send.

Is this issue a bug or is it by design?

**Comment by DrColossos** [comment]
After checking the code, for anyone looking for a solution why queues are not handled: this is not implemented. There is a seperate command queue:run, but its questionable if you want to run the cron queues one by one instead of via cron

If you want "core" behavior, drushs cron handling does this as expected.
