### ISSUE TITLE
[generate:service] does not update namespace if you specify other folder

### ISSUE THREAD

**Issue by botris** [hechoendrupal/drupal-console#3994]
### Problem/Motivation
When you run generate:service and during question "Enter the path for the services" you enter "src/Services" the files get created in the correct folder.
But the namespace in module.services.yml and service file and service interface file are all missing the "Services" folder in the namespace.

**Comment by reganking** [comment]
To expand ...

It sounds like you expect auto-detection of the namespace when called from the module folder (instead of from another directory where you would need to provide path / namespace). 

If you're using the generator to create the custom module in the first place, you won't be in the module folder to start with. However, if you're adding a service, or other element, afterwards, namespace auto-detection would seem a fair expectation. 

I use the generator for new modules, so expect to provide the namespace in the command options, e.g., `--name="my_module.my_service"`, `--class="Service"`, and `--path-service="/modules/custom/my_module/src/"`.

Generated services config `modules/custom/my_module/my_module.services.yml`:
```
services:
my_module.my_service:
    class: Drupal\my_module\Service
    ...
```
